### ISSUE TITLE
Scandir on multi-PB storage

### ISSUE THREAD

**Issue by David-Herman** [brmmm3/scandir-rs#4]
Hello,

My use case is to run scandir on a multi-PB storage volumes starting at the root of the mount point. I am running into an out of memory issue. It would be ideal to be able to clear entries in the scanner object via a kwarg in the results method, e.g. scanner.results(clear=True), so I can process the data during the scan process while avoiding an out of memory error.

**Comment by David-Herman** [comment]
In the interim, I have worked around this challenge by scanning to a max depth of N, getting all of the N depth folders, and then launching a scandir on each of those.

**Comment by brmmm3** [comment]
Ups, I forgot to answer you. Sorry. Newer versions of scandir-rs already have a solution for your issue.
The methods results and collect have a new option "store". If this option is set to false, then the results are not stored in the local object. This should fix your issue.

**Comment by David-Herman** [comment]
any performance impact? Can you document in https://github.com/brmmm3/scandir-rs/blob/master/doc/scandir.md and then close issue. thanks.

**Comment by brmmm3** [comment]
Updated documentation.
ATTENTION: For the 2.4.0 I have changed the API again.
The change is: The "store" parameter is not provided through the constructor ("new" method in Rust). The other methods don't have the store parameter anymore. The reason is that now the iterator also supports this new feature.

**Comment by David-Herman** [comment]
Hello,

I am revisiting the problem of multi-PB monitoring. I am seeing that the memory ticking upwards slowly over time. This demo example shows the issue.

The `len(scanner.results(only_new = False)[0]` looks ok (e.g. not indefinitely increasing) but the memory does appear to increase slowly. I have not seen changes in the memory change with the store value. Is entries cleared after the .entries() call?

```import scandir_rs
import time
import sys
import psutil
print(scandir_rs.__version__)
scanner = scandir_rs.Scandir(   path,
                    return_type = scandir_rs.ReturnType.Ext,
                    store       = False # Needed to avoid an out of memory issue
                    )
scanner.start()
time.sleep(1)
#print(dir(scanner))
print(psutil.virtual_memory().percent,len(scanner.entries(only_new = False)))
time.sleep(1)
print(psutil.virtual_memory().percent,len(scanner.entries(only_new = False)))
time.sleep(1)
print(psutil.virtual_memory().percent,len(scanner.entries(only_new = False)))
time.sleep(1)
print(psutil.virtual_memory().percent,len(scanner.entries(only_new = False)))
time.sleep(1)
print(psutil.virtual_memory().percent,len(scanner.results(only_new = False)[0]))
time.sleep(1)
print(psutil.virtual_memory().percent,len(scanner.results(only_new = False)[0]))
time.sleep(1)
print(psutil.virtual_memory().percent,len(scanner.results(only_new = False)[0]))
time.sleep(1)
print(psutil.virtual_memory().percent,len(scanner.results(only_new = False)[0]))
time.sleep(1)
print(psutil.virtual_memory().percent,len(scanner.results(only_new = False)[0]))
scanner.stop()
```


```
2.4.0
1.8 45743
1.9 88039
1.9 72794
2.0 125891
2.0 109367
2.1 90020
2.1 121629
2.1 93424
2.2 201607
```
