### ISSUE TITLE
Scandir hangs in version '2.0.5'

### ISSUE THREAD

**Issue by David-Herman** [brmmm3/scandir-rs#6]
I am running into issues in scandir-rs in version 2.05. I noticed a regression recently. The Scandir module either returns 0 results or the full file count but the scanner.busy() returns true. scanner.results_cnt() stays 0 or the full amount over time. No error is reported. I have noticed that my application eventually times out. In testing, some folder structures may return results where as others may hang followed by a timeout.

I am working on a linux HPC environment while running Scandir-rs on a mounted samba path.

I will downgrade and retest.

```   
scanner = Scandir(d,
                     skip_hidden = True,
                     return_type=ReturnType.Ext)
scanner.start()  
while scanner.busy():
   time.sleep(0.1)
   #never finishes here, either 0 results or N results. seems to time out at some point while not returning any results```

**Comment by brmmm3** [comment]
Please can you try again with latest version 2.3.1?

**Comment by David-Herman** [comment]
thanks for updating pypi. 2.3.1 solved the problem. thank you.
