### ISSUE TITLE
apple silicon builds in CI

### ISSUE THREAD

**Issue by jr200** [brmmm3/scandir-rs#8]
Hi,

Thanks for contributing this library - it must be one of the fastest directory walkers i've come across - especially on network shares. 

Would it be possible to include apple arm64 wheels as part of your CI. I took a [fork](https://github.com/jr200/scandir-rs) of your repo and made some small changes to [.github/workflow/ci.yaml](https://github.com/jr200/scandir-rs/commit/eefbe46d4a614257e308d02fcc56c9c3d3e29cd5) to build arm64 wheels.

Although the CI tests fail, some very light testing on my machine suggests it does indeed work.

**Comment by brmmm3** [comment]
Yes I can do this. I've removed Apple support in the past because the CI tests are failing most of the time. I can add Apple support again.

**Comment by jr200** [comment]
Much appreciated - thanks!

**Comment by jr200** [comment]
Confirmed this is working on mac arm64 with version 2.8.0. Thanks again.
